// we found the occasional... interesting word in the random word API
// to be safe, here are some cached results that are safe to display
// given that I don't know what all of them mean, it's possible there are some that do have inappropriate meanings
// but they'd probably be obscure enough to be safe
const cached = [
  ['cotinga', 'ressentiments', 'photoengravers', 'agonal', 'sapors' ],
  ['forefathers', 'fibril', 'emulating', 'glissandos', 'slackening' ],
  ['precenting', 'pointedness', 'cantatrice', 'classico', 'girds' ],
  ['arrowed', 'bourrees', 'stereotype', 'luteum', 'pavement' ],
  ['staunchness', 'tar', 'adolescence', 'latte', 'crowdedly' ],
  ['natriuresis', 'decimalizations', 'custom', 'reversions', 'uncinus' ],
  ['provincialize', 'cabstand', 'temptations', 'meadowlark', 'obstructor' ],
  ['contaminate', 'veniremen', 'sneakier', 'acorns', 'republishes' ],
  ['cancelers', 'mesopause', 'arrowworms', 'cosmetologists', 'gritters' ],
  ['franserias', 'honorarily', 'substratums', 'voltage', 'hydrophilic' ],
  ['carriageways', 'chauffer', 'eudaemonism', 'hegumenos', 'graywackes' ],
  ['boinks', 'sonnetted', 'coeditors', 'constellating', 'turfski' ],
  ['zayins', 'caseloads', 'meteoric', 'smoothen', 'cosignatory' ],
  ['koodoo', 'reddles', 'prostatism', 'backwards', 'bestsellerdom' ],
  ['dizzily', 'coffles', 'milages', 'denotements', 'semiwild' ],
  ['erepsin', 'interabang', 'milts', 'synecdoches', 'ressentiment' ],
  ['hobber', 'merchantmen', 'wimping', 'echard', 'disputing' ],
  ['handmade', 'movement', 'unmercifully', 'frontage', 'intrants' ],
  ['tyrannising', 'caravanserai', 'decisioned', 'empennages', 'teemingnesses' ],
  ['sended', 'rucks', 'overdeveloped', 'effacing', 'acetamids' ],
  ['femininenesses', 'kiwifruit', 'transistorising', 'lexes', 'inflectionally' ],
  ['egalitarians', 'sittings', 'pluralities', 'reorientated', 'marcellers' ],
  ['suns', 'send', 'marsupia', 'pogrom', 'insoul' ],
  ['nonpayment', 'commodious', 'mecamylamine', 'crumbums', 'lanosities' ],
  ['misquoted', 'solving', 'marls', 'any', 'chocolatiers' ],
  ['checkmates', 'lactases', 'squeeze', 'reversibilities', 'implodes' ],
  ['outgnawed', 'graveness', 'jackleg', 'emeute', 'lottes' ],
  ['jealousy', 'gamopetalous', 'berimbau', 'reparable', 'archaic' ],
  ['enrich', 'longest', 'disillusioned', 'hypostatize', 'strobil' ],
  ['decortication', 'ritual', 'smilaxes', 'spurriers', 'copperplates' ],
  ['acrolith', 'betta', 'hellhole', 'unbrake', 'uptick' ],
  ['blurbing', 'opponencies', 'commenters', 'coursed', 'immanency' ],
  ['gazumper', 'unissued', 'befret', 'enlistment', 'waked' ],
  ['mused', 'explicative', 'recessional', 'relying', 'parishioners' ],
  ['anacreontics', 'ashes', 'refortify', 'selloff', 'apparition' ],
  ['relines', 'searched', 'flannelling', 'deisms', 'leaviest' ],
  ['dogmatics', 'rods', 'floweret', 'trigonous', 'semiconducting' ],
  ['fortuitousness', 'sedimentologist', 'firedamp', 'conscripting', 'boschboks' ],
  ['absence', 'needinesses', 'wigwam', 'interlarding', 'colicins' ],
  ['aoristically', 'noisemakings', 'unquestioned', 'slagged', 'parcels' ],
  ['tromped', 'brakeman', 'rainiest', 'grooms', 'heteromorphisms' ],
  ['dashpot', 'redetermining', 'list', 'pinewoods', 'precincts' ],
  ['antae', 'canniest', 'bravers', 'nonart', 'sleepwear' ],
  ['gizzard', 'gloat', 'punto', 'graces', 'delectable' ],
  ['stimulant', 'sublingual', 'dogtooth', 'trepangs', 'restores' ],
  ['electrofishings', 'propitiously', 'mincy', 'decencies', 'droned' ],
  ['rebuild', 'tegg', 'siffleur', 'superspies', 'vibrate' ],
  ['afternoons', 'bogle', 'doolees', 'husklike', 'ungirded' ],
  ['stenotypes', 'rockier', 'gluey', 'tackier', 'pandered' ],
  ['superposes', 'disenthralling', 'etuis', 'xenopuses', 'makos' ],
  ['honours', 'flabbergasting', 'nutter', 'glimpsed', 'misgauging' ],
  ['newlyweds', 'tiering', 'sidepiece', 'spatular', 'chimichangas' ],
  ['rereview', 'witticisms', 'deistically', 'expired', 'buys' ],
  ['galingale', 'complainers', 'regimens', 'confutations', 'clandestinities' ],
  ['coactions', 'neuroticism', 'aphetic', 'buddleias', 'rhomboid' ],
  ['travoises', 'stung', 'sepulchral', 'wildfowlers', 'mimeographs' ],
  ['taximen', 'tympanic', 'baguette', 'doughnut', 'equationally' ],
  ['recusancies', 'proctodaeum', 'daughters', 'outblesses', 'mensa' ],
  ['prototrophs', 'populated', 'visibly', 'breach', 'symposiums' ],
  ['honeyguide', 'hotshots', 'toured', 'congenerous', 'peyotls' ],
  ['outsized', 'melanian', 'constraints', 'electroacoustic', 'enwheel' ],
  ['casernes', 'tailspinning', 'lockdowns', 'extrema', 'agelessnesses' ],
  ['viosterol', 'intelligibly', 'shortchanged', 'duded', 'misreading' ],
  ['bellies', 'filefishes', 'dotingly', 'contending', 'inferrer' ],
  ['glucoses', 'continued', 'toddies', 'preyer', 'mungoose' ],
  ['siennas', 'crummy', 'valves', 'insensitiveness', 'dinged' ],
  ['drupe', 'savins', 'millstream', 'corespondent', 'malmiest' ],
  ['bituminizing', 'echinococcoses', 'preceptors', 'corrosivenesses', 'taters' ],
  ['fertilities', 'miffed', 'psychiatries', 'astringing', 'objectivist' ],
  ['readjusted', 'aurorean', 'matriculant', 'bacchantes', 'lymphogranuloma' ],
  ['distome', 'infractions', 'butyryl', 'butcherer', 'cheapener' ],
  ['denizens', 'lobotomies', 'unabiding', 'batman', 'brachs' ],
  ['magnetised', 'arsenical', 'caterers', 'auks', 'placement' ],
  ['procure', 'bestrews', 'cathect', 'intergradation', 'coronary' ],
  ['observes', 'centrums', 'polarographies', 'bolloxed', 'truncations' ],
  ['baseman', 'myxomatous', 'scintillation', 'subtile', 'intercoms' ],
  ['intellectual', 'classists', 'scummily', 'sisterhoods', 'seamarks' ],
  ['confessionals', 'jollied', 'tarrying', 'finalization', 'fictitious' ],
  ['kain', 'jows', 'hebetic', 'mizenmast', 'improbable' ],
  ['beclasps', 'minaret', 'poutful', 'saggers', 'deprivals' ],
  ['envying', 'lamplighter', 'bastioned', 'stiffener', 'aerodynamic' ],
  ['blintz', 'handclasps', 'daunts', 'contested', 'trowelled' ],
  ['mischoosing', 'outcropping', 'subspecific', 'mightier', 'cosmolined' ],
  ['densitometry', 'bedcovers', 'tipstaff', 'yellowtails', 'outjockeyed' ],
  ['micromho', 'mopboard', 'grimier', 'dissonant', 'crossbow' ],
  ['voguish', 'abyssal', 'multipath', 'peeresses', 'autografting' ],
  ['sanctimonies', 'redip', 'plenteous', 'bullet', 'leviable' ],
  ['introducer', 'selfwards', 'reanimate', 'revitalization', 'dieing' ],
  ['crossbanding', 'echeloned', 'stereograms', 'watchables', 'postin' ],
  ['recriminatory', 'hareem', 'riffraff', 'splakes', 'noncandidacy' ],
  ['hamantasch', 'silvans', 'potheens', 'legitimised', 'yah' ],
  ['mucosities', 'rejectors', 'cryonics', 'rhinal', 'canakins' ],
  ['jennies', 'bromates', 'selfhood', 'carbonation', 'muzzler' ],
  ['penal', 'unhealthier', 'drumbeatings', 'hawker', 'orinasals' ],
  ['feyness', 'oversaturation', 'dozinesses', 'hydro', 'spiritualism' ],
  ['ascomycetous', 'interplayed', 'rezones', 'benzanthracenes', 'shoetree' ],
  ['mauling', 'memsahibs', 'ore', 'overmelted', 'disbudding' ],
  ['jealous', 'hemelytron', 'creepier', 'predestination', 'onomasticians' ],
  ['sandshoe', 'chortles', 'holies', 'guiling', 'dulse' ],
  ['uncensorious', 'meritoriously', 'scrappiest', 'finito', 'screwballs' ],
  ['haircutter', 'unpliant', 'candent', 'nonreactors', 'audiogenic' ],
  ['sporozoal', 'compensable', 'witnessed', 'hormone', 'perigeal' ],
  ['carminative', 'seawalls', 'whirrying', 'blamers', 'champaks' ],
  ['farmer', 'joviality', 'livest', 'cyberspaces', 'solenodon' ],
];

let cachedCounter = 0;

const getCachedData = () => {
  cachedCounter++;
  // must be a promise to match the actual API call
  return new Promise((resolve, reject) => resolve(cached[cachedCounter % cached.length]));
};

module.exports = getCachedData;